#!/bin/sh

chosen=$(
    printf '%s\n' \
        "󰌾  Lock" \
        "󰍃  Logout" \
        "󰐥  Shutdown" \
        "󰜉  Reboot" |
    dmenu \
        -i \
        -fn 'JetBrainsMono Nerd Font-12' \
        -nb '#000000' \
        -nf '#F2F4F8' \
        -sb '#4C7899' \
        -sf '#FFFFFF' \
        -p 'Power:'
)

case "$chosen" in
    "󰌾  Lock")
        exec i3lock \
            --nofork \
            --show-failed-attempts \
            --ignore-empty-password \
            --tiling \
            -c 000000
        ;;

    "󰍃  Logout")
        exec i3-msg exit
        ;;

    "󰐥  Shutdown")
        systemctl poweroff
        ;;

    "󰜉  Reboot")
        systemctl reboot
        ;;

    *)
        exit 0
        ;;
esac
