#!/bin/sh

wall_dir="${HOME}/.config/wallpapers"

wall_selection=$(
    find "$wall_dir" \
        -maxdepth 1 \
        -type f \
        \( \
            -iname "*.jpg" \
            -o -iname "*.jpeg" \
            -o -iname "*.png" \
            -o -iname "*.webp" \
        \) \
        -exec basename {} \; |
    sort |
    dmenu \
        -i \
        -fn 'JetBrainsMono Nerd Font-12' \
        -nb '#000000' \
        -nf '#F2F4F8' \
        -sb '#4C7899' \
        -sf '#FFFFFF' \
        -p 'Wallpaper:'
)

[ -n "$wall_selection" ] || exit 0

wallpaper="${wall_dir}/${wall_selection}"

feh --bg-fill "$wallpaper" &

printf '%s\n' "$wallpaper" > "${HOME}/.config/default"
