# i3 Electric Blue Kitty Theme

background            #000000
foreground            #FFFFFF

cursor                #00A8FF

selection_background  #0057FF
selection_foreground  #FFFFFF


# Black
color0                #000000
color8                #333333

# Red
color1                #FF0033
color9                #FF3355

# Green
color2                #00FF41
color10               #39FF14

# Yellow
color3                #FFD600
color11               #FFFF33

# Blue
color4                #008CFF
color12               #00B7FF

# Magenta
color5                #D500FF
color13               #FF33FF

# Cyan
color6                #00E5FF
color14               #66FFFF

# White
color7                #E8F1FF
color15               #FFFFFF


# Tabs

active_tab_foreground   #FFFFFF
active_tab_background   #008CFF

inactive_tab_foreground #888888
inactive_tab_background #111111