(deftheme debian-i3
  "https://github.com/giovanni-iannaccone/dot-configs")

(custom-theme-set-faces
 'debian-i3
 '(cursor ((t (:background "#237AD3"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#85DDFF"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#d0d7de"))))
 '(highlight ((t (:background "#237AD3" :foreground "#171F24"))))
 '(region ((t (:extend t :background "#113d69"))))
 '(shadow ((t (:foreground "#37474F"))))
 '(secondary-selection ((t (:extend t :background "#777778"))))
 '(trailing-whitespace ((t (:background "#D16969"))))
 '(font-lock-bracket-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-builtin-face ((t (:foreground "#C586C0"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#4e5b55"))))
 '(font-lock-constant-face ((t (:foreground "#339CDB"))))
 '(font-lock-delimiter-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#777778"))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-constant-face))))
 '(font-lock-escape-face ((t (:inherit font-lock-regexp-grouping-backslash))))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:foreground "#237AD3"))))
 '(font-lock-keyword-face ((t (:foreground "#339CDB"))))
 '(font-lock-negation-char-face ((t (:foreground "#85DDFF" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#B5CEA8"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit bold :foreground "#85DDFF"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#85DDFF" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#85DDFF" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#85DDFF"))))
 '(font-lock-type-face ((t (:foreground "#35CDAF"))))
 '(font-lock-variable-name-face ((t (:foreground "#85DDFF"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "#d0d7de3" :underline t :weight bold))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#4b474c" :inherit (default)))))
 '(header-line ((t (:inherit mode-line))))
 '(tooltip ((t (:foreground "#d4d4d4" :background "#121212"))))
 '(mode-line ((t (:background "#D29922" :foreground "#0d1117"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#d4d4d4"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#0d1117" :foreground "#d0d7de"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#171F24" :background "#D16969"))))
 '(lazy-highlight ((t (:weight bold :foreground "#d4d4d4" :background "#4b474c"))))
 '(match ((t (:weight bold :foreground "#579C4C" :background "#171F24"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#0d1117" :foreground "#d4d4d4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 128 :width normal :foundry "JB" :family "JetBrainsMono Nerd Font")))))

(provide-theme 'debian-i3)
