[[opener.zathura]]
run = "zathura %s"
orphan = true
for = "unix"
desc = "Zathura"

[[opener.mpv]]
run = "mpv %s"
orphan = true
for = "unix"
desc = "MPV"

[[open.prepend_rules]]
mime = "application/pdf"
use = "zathura"

[[open.prepend_rules]]
mime = "video/*"
use = "mpv"